-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- CREATE TABLES
CREATE TABLE category(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(64) NOT NULL
);

CREATE TABLE product(
  id NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(64) NOT NULL,
  price DECIMAL(7,2),
  category_id INT
);

CREATE TABLE tag (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(32)
);

CREATE TABLE producttag (
  id  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT,
  tag_id INT
);
